# Generated by Django 5.1 on 2024-08-14 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarberModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'barbers',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('duration', models.IntegerField(choices=[(1, '1 Hora'), (2, '2 Horas'), (3, '3 Horas')])),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='SchedulModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('barber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='services.barbermodel')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
    ]
